#pragma once

#include "types/camera.hpp"
#include "types/config.hpp"
#include "types/local_geometry.hpp"
#include "types/material.hpp"
#include "types/mesh.hpp"
#include "types/ray.hpp"
#include "types/shader.hpp"
#include "types/strong_hit.hpp"
#include "types/texture.hpp"
#include "types/transform.hpp"
#include "types/triangle.hpp"
#include "types/vertex.hpp"
#include "types/weak_hit.hpp"
